"""
This subpackage contains code for quickly analyzing certain types of information from
the simulation outputs.

This includes information such as the average monte carlo move sizes for the last
handful of snapshots, the autocorrelation times, and so on.
"""

from pimc_simpy.quick_analysis._read_project_data_common import read_project_kinetic_energy
from pimc_simpy.quick_analysis._read_project_data_common import read_project_pair_potential_energy
from pimc_simpy.quick_analysis._read_project_data_common import read_project_triplet_potential_energy
from pimc_simpy.quick_analysis._read_project_data_common import read_project_quadruplet_potential_energy
from pimc_simpy.quick_analysis._read_project_data_common import read_project_rms_centroid_distance
from pimc_simpy.quick_analysis._read_project_data_common import read_project_absolute_centroid_distance
from pimc_simpy.quick_analysis._read_project_data_common import read_project_centre_of_mass_step_size
from pimc_simpy.quick_analysis._read_project_data_common import read_project_bisection_multibead_position_move_acceptance
from pimc_simpy.quick_analysis._read_project_data_common import read_project_single_bead_position_move_acceptance
from pimc_simpy.quick_analysis._read_project_data_common import read_project_centre_of_mass_position_move_acceptance
from pimc_simpy.quick_analysis._read_project_data_common import read_project_bisection_multibead_position_move_info
from pimc_simpy.quick_analysis._read_project_data_common import read_project_timer
from pimc_simpy.quick_analysis._read_project_data_common import read_project_radial_dist_histogram
from pimc_simpy.quick_analysis._read_project_data_common import read_project_centroid_radial_dist_histogram
from pimc_simpy.quick_analysis._read_project_data_common import read_project_box_sides
