"""
This subpackage contains code for quickly analyzing certain types of information from
the simulation outputs.

This includes information such as the average monte carlo move sizes for the last
handful of snapshots, the autocorrelation times, and so on.
"""

from pimc_simpy.quick_analysis._converged_monte_carlo_steps import read_converged_bisection_multibead_position_move_info
from pimc_simpy.quick_analysis._converged_monte_carlo_steps import read_converged_centre_of_mass_step_size
from pimc_simpy.quick_analysis._converged_monte_carlo_steps import write_converged_bisection_multibead_position_move_info_between
from pimc_simpy.quick_analysis._converged_monte_carlo_steps import write_converged_bisection_multibead_position_move_info_last
from pimc_simpy.quick_analysis._converged_monte_carlo_steps import write_converged_centre_of_mass_step_size_between
from pimc_simpy.quick_analysis._converged_monte_carlo_steps import write_converged_centre_of_mass_step_size_last

from pimc_simpy.quick_analysis._read_project_data_common import ProjectDataReader
