"""
This module contains code for reading information about the ideal Monte Carlo step sizes
from files generated by the simulation code.
"""

# PLAN
# - get the ideal COM step size
# - get the ideal bisection level info

# - I should create functions for reading in the data from files with particular formats
#   - right now I just have:
#     - histogram [DONE?]
#     - single value data
#     - double value data
#     - triple value data

# - implement slicing for PropertyData object, so I can skip certain parts of the data
